### ISSUE TITLE
compilation issue

### ISSUE THREAD

**Issue by kondors1995** [frap129/angler#3]
https://github.com/frap129/angler/blob/1b149bba4d0a0475422acdeeec96a567f6b40ad7/drivers/cpufreq/cpufreq_electron.c#L469

Hello i am having issues with this gov compilation 

drivers/cpufreq/cpufreq_electron.c: In function 'cpufreq_electron_timer':
drivers/cpufreq/cpufreq_electron.c:469:23: error: passing argument 1 of 'sched_get_cpus_busy' from incompatible pointer type [-Werror=incompatible-pointer-types]
   sched_get_cpus_busy(ppol->cpu_busy_times,
                       ^~~~
In file included from ./arch/arm64/include/asm/compat.h:25:0,
                 from ./arch/arm64/include/asm/stat.h:23,
                 from include/linux/stat.h:5,
                 from include/linux/sysfs.h:21,
                 from include/linux/kobject.h:21,
                 from include/linux/device.h:17,
                 from include/linux/node.h:17,
                 from include/linux/cpu.h:16,
                 from drivers/cpufreq/cpufreq_electron.c:19:
include/linux/sched.h:2067:13: note: expected 'struct sched_load *' but argument is of type 'long unsigned int *'
 extern void sched_get_cpus_busy(struct sched_load *busy,
             ^~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:257: drivers/cpufreq/cpufreq_electron.o] Error 1
make[2]: *** Waiting for unfinished jobs....
  CC      fs/ext3/file.o

Source https://github.com/kondors1995/android_kernel_xiaomi_msm8953/tree/dev/or

**Comment by frap129** [comment]
Interactive based governors are schedular dependant and tend to not very portable
